import { useEffect, useState } from "react";
import { dataUrlToBytes } from "@/shared/lib/fileContent";
import { getFileName } from "@/shared/lib/utils";

/**
 * Sandbox flags for iframes hosting converter-generated documents:
 * - allow-scripts: pptx/docx documents embed small inline fit/autofit scripts
 * - allow-popups + escape: hyperlinks in the documents open via target=_blank,
 *   which a sandboxed iframe silently blocks without these
 *
 * The HTML is generated by our converters from escaped document content with
 * no external resources, so scripting it is safe.
 */
export const OFFICE_IFRAME_SANDBOX = "allow-scripts allow-popups allow-popups-to-escape-sandbox";

/**
 * Shared loader for the office preview editors: decodes the artifact's binary
 * data URL, runs it through the given converter, and reports failure so the
 * editor can fall back to the extracted-markdown preview.
 *
 * `convert` must be referentially stable (a module-level function).
 */
export function useOfficeConversion<T>(
  path: string,
  content: string,
  contentType: string | undefined,
  convert: (file: File) => Promise<T>,
): { result: T | null; failed: boolean } {
  const [result, setResult] = useState<T | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setResult(null);
    setFailed(false);

    const parsed = dataUrlToBytes(content);
    if (!parsed) {
      setFailed(true);
      return;
    }

    // `.slice()` narrows the backing buffer to a fresh ArrayBuffer for BlobPart
    const file = new File([parsed.bytes.slice()], getFileName(path), {
      type: contentType ?? parsed.mimeType,
    });

    convert(file)
      .then((res) => {
        if (!cancelled) setResult(res);
      })
      .catch((e) => {
        console.error(`Office preview failed for ${path}, falling back to text preview:`, e);
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
    };
  }, [path, content, contentType, convert]);

  return { result, failed };
}
